name: Prepare release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: Version type
        required: true
        default: minor
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Update versions in package.json and package-lock.json
        id: version
        run: |
          npm version ${{ github.event.inputs.version_type }} --no-git-tag-version
          NEW_VERSION=$(npm pkg get version | tr -d \")
          echo "New version (${{ github.event.inputs.version_type }}): $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update changelog to version ${{ steps.version.outputs.new_version }}
        run: |
          node build/releaser.mjs update-changelog ${{ steps.version.outputs.new_version }}

      - name: Configure Git
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"

      - name: Create pull request
        # https://github.com/peter-evans/create-pull-request/releases/tag/v7.0.8
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: bot/prepare-release-v${{ steps.version.outputs.new_version }}
          commit-message: |
            Prepare for the v${{ steps.version.outputs.new_version }} release

            This commit was generated by a GitHub Action workflow. It was triggered
            by ${{ github.actor }}.
          signoff: true
          delete-branch: true
          title: 'Prepare for the v${{ steps.version.outputs.new_version }} release (triggered by ${{ github.actor }})'
          body: |
            This pull request was generated by `./github/workflows/prepare-release.yml`.

            It modifies the following three files:
            - `CHANGELOG.md` (update the section header to ${{ steps.version.outputs.new_version }} with today's date in UTC and the links at the bottom)
            - `package.json` (update version number to ${{ steps.version.outputs.new_version }} )
            - `package-lock.json` (update version number to ${{ steps.version.outputs.new_version }})
          draft: false
          add-paths: |
            CHANGELOG.md
            package.json
            package-lock.json
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
