name: Verify Signed-off-by or GPG Signature

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check each commit for sign-off or GPG signature
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          signoff_regex="^Signed-off-by: [A-Za-z .'-]+ <[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}>$"
          commits=$(gh pr view ${{ github.event.pull_request.number }} --json commits -q ".commits[].oid")

          missing=0

          for sha in $commits; do
            echo "🔍 Checking commit $sha..."
            message=$(git log -1 --pretty=format:%B "$sha")

            if echo "$message" | grep -Eq "$signoff_regex"; then
              echo "✔ Signed-off-by line found."
              continue
            fi

            is_verified=$(gh api repos/${{ github.repository }}/commits/$sha --jq '.commit.verification.verified')
            if [ "$is_verified" = "true" ]; then
              echo "✔ Verified GPG signature found."
              continue
            fi

            echo "::error file=.git/COMMIT_EDITMSG::❌ Commit $sha is missing both a valid Signed-off-by line and a verified GPG signature."
            missing=$((missing + 1))
          done

          if [ "$missing" -gt 0 ]; then
            echo "❌ Some commits are not properly signed."
            exit 1
          fi
