name: Verify commit signatures
on:
  pull_request:
    branches:
      - '**'

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run commit sign-off check script
        run: |
          .github/scripts/check-commits.sh "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
